previews:
  generation: automatic

services:
  - type: web
    name: paraguay-hub-backend
    runtime: python
    rootDir: backend
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      
  - type: web
    name: paraguay-hub-frontend
    runtime: static
    rootDir: frontend
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist


  